---
name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ['1.10', '1.11']
        otp: ['22', '23']
    services:
      redis:
        image: redis
        ports: [ "6379:6379" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install (os)
        run: apk add --no-cache gcc g++ git make musl-dev tar zstd

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Get deps cache
        uses: actions/cache@v2
        with:
          path: deps/
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Get build cache
        uses: actions/cache@v2
        with:
          path: _build/test/
          key: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile
      - name: Run Tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_POOL_SIZE: 1
      - name: Run Credo
        run: mix credo
